export const TagValues = {
  ['react']: 'React',
  ['javascript']: 'JavaScript',
  ['prisma']: 'Prisma',
  ['typescript']: 'TypeScript',
  ['nextjs']: 'Next.js',
  ['tailwindcss']: 'Tailwind CSS',
  ['css']: 'CSS',
  ['html']: 'HTML',
  ['nodejs']: 'Node.js',
  ['backend']: 'Backend',
  ['frontend']: 'Frontend',
  ['graphql']: 'GraphQL',
  ['redux']: 'Redux',
  ['testing']: 'Testing',
  ['web-security']: 'Web Security',
  ['api']: 'API',
  ['accessibility']: 'Accessibility',
  ['performance']: 'Performance',
  ['software-development']: 'Software Development',
  ['ux']: 'UX',
  ['git']: 'Git',
  ['gatsby']: 'Gatsby',
  ['svg']: 'SVG',
  ['serverless']: 'Serverless',
  ['dom']: 'DOM',
  ['astro']: 'Astro',
  ['sustainability']: 'Sustainability',
}
