// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type BlogDocumentDataSlicesSlice = AllblogpostsSlice | LatestblogpostsSlice

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, 'blog', Lang>

type BlogPostDocumentDataSlicesSlice = RichtextSlice

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    'blog_post',
    Lang
  >

/**
 * Content for Blogcategory documents
 */
interface BlogcategoryDocumentData {
  /**
   * Title field in *Blogcategory*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogcategory.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField
}

/**
 * Blogcategory document from Prismic
 *
 * - **API ID**: `blogcategory`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogcategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogcategoryDocumentData>,
    'blogcategory',
    Lang
  >

/**
 * Item in *Footer → Navigation*
 */
export interface FooterDocumentDataNavigationItem {
  /**
   * Link field in *Footer → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * Icon field in *Footer → Navigation*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigation[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<'Mail' | 'GitHub' | 'LinkedIn' | 'RSS'>
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * linktotop field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.linktotop
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linktotop: prismic.KeyTextField

  /**
   * Navigation field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<FooterDocumentDataNavigationItem>>

  /**
   * Content field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, 'footer', Lang>

/**
 * Item in *Header → Navigation*
 */
export interface HeaderDocumentDataNavigationItem {
  /**
   * Navigationitem field in *Header → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].navigationitem
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigationitem: prismic.LinkField

  /**
   * Navigationlabel field in *Header → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].navigationlabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  navigationlabel: prismic.KeyTextField
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo: prismic.LinkField

  /**
   * Navigation field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<HeaderDocumentDataNavigationItem>>
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, 'header', Lang>

type HomepageDocumentDataSlicesSlice =
  | LatestblogpostsSlice
  | TestimonialsSlice
  | CtaSlice
  | IndexstageSlice
  | RichtextSlice
  | ProjectsSlice
  | PageheaderSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >

type PageDocumentDataSlicesSlice =
  | TextmediaSlice
  | CtaSlice
  | ProjectsSlice
  | PageheaderSlice
  | RichtextSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>

export type AllDocumentTypes =
  | BlogDocument
  | BlogPostDocument
  | BlogcategoryDocument
  | FooterDocument
  | HeaderDocument
  | HomepageDocument
  | PageDocument

/**
 * Default variation for Allblogposts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllblogpostsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>

/**
 * Slice variation for *Allblogposts*
 */
type AllblogpostsSliceVariation = AllblogpostsSliceDefault

/**
 * Allblogposts Shared Slice
 *
 * - **API ID**: `allblogposts`
 * - **Description**: Allblogposts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllblogpostsSlice = prismic.SharedSlice<
  'allblogposts',
  AllblogpostsSliceVariation
>

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Label field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CtaSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<'cta', CtaSliceVariation>

/**
 * Primary content in *Indexstage → Default → Primary*
 */
export interface IndexstageSliceDefaultPrimary {
  /**
   * Image field in *Indexstage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: indexstage.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Headline field in *Indexstage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: indexstage.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField

  /**
   * Text field in *Indexstage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: indexstage.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Link field in *Indexstage → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: indexstage.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * Linklabel field in *Indexstage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: indexstage.default.primary.linklabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel: prismic.KeyTextField
}

/**
 * Default variation for Indexstage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IndexstageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<IndexstageSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Indexstage*
 */
type IndexstageSliceVariation = IndexstageSliceDefault

/**
 * Indexstage Shared Slice
 *
 * - **API ID**: `indexstage`
 * - **Description**: Indexstage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IndexstageSlice = prismic.SharedSlice<
  'indexstage',
  IndexstageSliceVariation
>

/**
 * Default variation for Latestblogposts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LatestblogpostsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>

/**
 * Slice variation for *Latestblogposts*
 */
type LatestblogpostsSliceVariation = LatestblogpostsSliceDefault

/**
 * Latestblogposts Shared Slice
 *
 * - **API ID**: `latestblogposts`
 * - **Description**: Latestblogposts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LatestblogpostsSlice = prismic.SharedSlice<
  'latestblogposts',
  LatestblogpostsSliceVariation
>

/**
 * Primary content in *Pageheader → Default → Primary*
 */
export interface PageheaderSliceDefaultPrimary {
  /**
   * Headline field in *Pageheader → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: pageheader.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField
}

/**
 * Default variation for Pageheader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageheaderSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<PageheaderSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Pageheader*
 */
type PageheaderSliceVariation = PageheaderSliceDefault

/**
 * Pageheader Shared Slice
 *
 * - **API ID**: `pageheader`
 * - **Description**: Pageheader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageheaderSlice = prismic.SharedSlice<
  'pageheader',
  PageheaderSliceVariation
>

/**
 * Item in *Projects → Default → Primary → Projects*
 */
export interface ProjectsSliceDefaultPrimaryProjectsItem {
  /**
   * Image field in *Projects → Default → Primary → Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.projects[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Content field in *Projects → Default → Primary → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.projects[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * Link field in *Projects → Default → Primary → Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.projects[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
  /**
   * Anchor field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.anchor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  anchor: prismic.KeyTextField

  /**
   * Intro field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  intro: prismic.RichTextField

  /**
   * Projects field in *Projects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.projects[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<
    Simplify<ProjectsSliceDefaultPrimaryProjectsItem>
  >

  /**
   * Cta field in *Projects → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField

  /**
   * Cta Label field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField

  /**
   * Cta Style field in *Projects → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Inline Link
   * - **API ID Path**: projects.default.primary.ctaStyle
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  ctaStyle: prismic.SelectField<'Inline Link' | 'Button', 'filled'>
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ProjectsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<
  'projects',
  ProjectsSliceVariation
>

/**
 * Primary content in *Richtext → Default → Primary*
 */
export interface RichtextSliceDefaultPrimary {
  /**
   * Richtext field in *Richtext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: richtext.default.primary.richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  richtext: prismic.RichTextField
}

/**
 * Default variation for Richtext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichtextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<RichtextSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Richtext*
 */
type RichtextSliceVariation = RichtextSliceDefault

/**
 * Richtext Shared Slice
 *
 * - **API ID**: `richtext`
 * - **Description**: Richtext
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichtextSlice = prismic.SharedSlice<
  'richtext',
  RichtextSliceVariation
>

/**
 * Item in *Testimonials → Default → Primary → Item*
 */
export interface TestimonialsSliceDefaultPrimaryItemItem {
  /**
   * Text field in *Testimonials → Default → Primary → Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.item[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Name field in *Testimonials → Default → Primary → Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.item[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Link field in *Testimonials → Default → Primary → Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.item[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * Linklabel field in *Testimonials → Default → Primary → Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.item[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel: prismic.KeyTextField

  /**
   * Image field in *Testimonials → Default → Primary → Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.item[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Item field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.item[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  item: prismic.GroupField<Simplify<TestimonialsSliceDefaultPrimaryItemItem>>
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  'testimonials',
  TestimonialsSliceVariation
>

/**
 * Primary content in *Textmedia → Default → Primary*
 */
export interface TextmediaSliceDefaultPrimary {
  /**
   * Image field in *Textmedia → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: textmedia.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Text field in *Textmedia → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: textmedia.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * Default variation for Textmedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextmediaSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TextmediaSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Textmedia*
 */
type TextmediaSliceVariation = TextmediaSliceDefault

/**
 * Textmedia Shared Slice
 *
 * - **API ID**: `textmedia`
 * - **Description**: Textmedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextmediaSlice = prismic.SharedSlice<
  'textmedia',
  TextmediaSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      BlogcategoryDocument,
      BlogcategoryDocumentData,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataNavigationItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavigationItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AllblogpostsSlice,
      AllblogpostsSliceVariation,
      AllblogpostsSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      IndexstageSlice,
      IndexstageSliceDefaultPrimary,
      IndexstageSliceVariation,
      IndexstageSliceDefault,
      LatestblogpostsSlice,
      LatestblogpostsSliceVariation,
      LatestblogpostsSliceDefault,
      PageheaderSlice,
      PageheaderSliceDefaultPrimary,
      PageheaderSliceVariation,
      PageheaderSliceDefault,
      ProjectsSlice,
      ProjectsSliceDefaultPrimaryProjectsItem,
      ProjectsSliceDefaultPrimary,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
      RichtextSlice,
      RichtextSliceDefaultPrimary,
      RichtextSliceVariation,
      RichtextSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryItemItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TextmediaSlice,
      TextmediaSliceDefaultPrimary,
      TextmediaSliceVariation,
      TextmediaSliceDefault,
    }
  }
}
