// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  indexstage: dynamic(() => import('./Indexstage')),
  pageheader: dynamic(() => import('./Pageheader')),
  projects: dynamic(() => import('./Projects')),
  richtext: dynamic(() => import('./Richtext')),
}
